def agentLabel = ""
pipeline{
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    parameters {
        string(name: 'testsToRun',description: '' )
        string(name: 'runnerJarPath', defaultValue: 'C:\\dev\\shift\\silk-central-shift\\execution-wrapper\\target\\octane-shift-execution-wrapper-4.20-SNAPSHOT.jar', description: "")
        string(name: 'nunit2',defaultValue: '\"D:\\from C\\myFolder\\nunit\\NUnit-2.7.1\\bin\\nunit-console.exe\"',description: '' )
        string(name: 'nunit3',defaultValue: '\"D:\\from C\\myFolder\\netcoreapp3.1\\Nunit\\nunit3-console.exe\"' )
        string(name: 'suiteId',description: '' )
        string(name: 'suiteRunId',description: '' )
    }
    environment {
            AUTH_TOKEN = credentials('AndreiGithubCredentials')
    }
    stages {

        stage('setTag') {
            steps {
                script {
                    agentLabel = bat(script: "echo myTag1", returnStdout: true).trim().readLines().drop(1).join(" ")
                }
            }
        }

        stage('Run Tests') {
            agent{
                label agentLabel
            }
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'AndreiSVN', usernameVariable: 'github_user', passwordVariable: 'github_password')]) {
                        bat 'echo START'
                        bat 'cd test-execution'
                        bat 'call npm install'
                        bat 'call npm run build'
                        bat 'call npm run start-nunit $params.testsToRun $params.runnerJarPath $params.nunit2 $params.nunit3 $params.suiteId $params.suiteRunId $params.github_user $params.github_password'
                        bat 'call command_to_execute.bat'
                        bat 'call java_command_to_execute.bat'
                    }
                }
            }

        }

    }
    post {
                failure {
                    cleanWs()
                }
                success {
                    archiveArtifacts artifacts: 'test-execution/java_command_to_execute.bat,test-execution/command_to_execute.bat,test-execution/testResults/*xml', onlyIfSuccessful: true
                    junit allowEmptyResults: true, testResults: 'test-execution/testResults/*xml'
                    cleanWs()
                }
                aborted {
                    cleanWs()
                }
            }

}
