def agentLabel = ""
pipeline{
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    parameters {
        string(name: 'testsToRunConverted',description: '' )
        string(name: 'runnerJarPath', defaultValue: 'C:\\dev\\shift\\silk-central-shift\\execution-wrapper\\target\\octane-shift-execution-wrapper-4.54-SNAPSHOT.jar', description: "")
        string(name: 'nunit2',defaultValue: 'D:\\myFolder\\NUnit-2.7.1\\bin\\nunit-console.exe',description: '' )
        string(name: 'nunit3',defaultValue: 'D:\\myFolder\\netcoreapp3.1\\Nunit\\nunit3-console.exe' )
        string(name: 'suiteId',description: '' )
        string(name: 'suiteRunId',description: '' )
    }

    stages {

        stage('setTag') {

            steps {
                dir('test-execution') {
                    bat 'npm install'
                    bat 'npm run build'
                    bat 'echo getting execution keywords from the test suite'
                    bat 'npm run start-init-execution-keywords %suiteId%"'
                    script {
                          agentLabel = readFile('execution_keywords.txt').trim()
                    }
                }

            }
        }

        stage('Run Tests') {
            agent{
                label agentLabel
            }
            steps {
                convertTestsToRun format:'', framework: 'mvnSurefire'
                script {
                    withCredentials([usernamePassword(credentialsId: 'PersonalGitHub', usernameVariable: 'github_user', passwordVariable: 'github_password')]) {
                        dir('test-execution') {
                            bat 'npm install'
                            bat 'npm run build'
                            bat 'call npm run start-nunit "%testsToRunConverted%" "%runnerJarPath%" %suiteId% %suiteRunId% %nunit2% %nunit3% %github_user% %github_password%'
                            bat 'call echo "running tests..."'
                            try {
                                bat 'call command_to_execute.bat'
                            } catch(err) {
                                bat 'echo Tests failed! Continue...'
                            }
                            bat 'call java_command_to_execute.bat'
                        }

                    }
                }
                archiveArtifacts artifacts: 'test-execution/java_command_to_execute.bat,test-execution/command_to_execute.bat,test-execution/testResults/**', onlyIfSuccessful: false
                junit allowEmptyResults: true, testResults: 'test-execution/testResults/*/*.xml'

            }

        }

    }
    post {
        always {
             // node(agentLabel) {
             //     dir('test-execution') {
             //         bat 'if exist test_sources rmdir test_sources /s /q'
             //         bat 'if exist testResults rmdir testResults /s /q'
             //         bat 'if exist command_to_execute.bat del command_to_execute.bat'
             //         bat 'if exist java_command_to_execute.bat del java_command_to_execute.bat'
             //     }
             // }
             cleanWs()
         }
        aborted {
            cleanWs()
            bat 'echo abort'
        }
    }

}
